import {describe,expect,it} from "vitest";import {renderToStaticMarkup} from "react-dom/server";import golden from "../../fixtures/aiPresentationFullGolden.json";
import {enumManifest,type EnumGroup} from "./enumManifest.generated";import {enumTranslationCatalog,translateEnum} from "./enumTranslations";import {fieldTranslationCatalog,translateField} from "./fieldTranslations";import {semanticKinds,SemanticBadge} from "./SemanticBadge";import {shadowText} from "./i18n";import {ReportSections} from "./ReportSections";import {AuditPanel,Levels,Macro,OrderFlow,Scenarios,TimeframeMatrix,Timeline} from "./AnalysisPanels";import {PositionPanel} from "./PositionPanel";import {HealthPanel} from "./HealthPanel";import {safeEnum} from "./formatters";import type {Presentation} from "./types";
const fixture=golden as unknown as Presentation;const labelsZh=shadowText("zh"),labelsEn=shadowText("en");
const render=(node:React.ReactNode)=>renderToStaticMarkup(<>{node}</>);

describe("complete typed enum i18n gate",()=>{
  it("covers every manifest value in zh and en with no empty label",()=>{for(const [group,values] of Object.entries(enumManifest.groups) as [EnumGroup,readonly string[]][]){for(const value of values){expect(enumTranslationCatalog[group][value].zh,`${group}.${value}.zh`).toBeTruthy();expect(enumTranslationCatalog[group][value].en,`${group}.${value}.en`).toBeTruthy();expect(translateEnum(group,value,"zh")).not.toContain("未知枚举");expect(translateEnum(group,value,"en")).not.toContain("Unknown enum");}}});
  it("uses explicit unknown fallback only for unsupported development values",()=>{expect(translateEnum("trend","FUTURE_VALUE","zh")).toBe("未知枚举（FUTURE_VALUE）");expect(translateEnum("trend","FUTURE_VALUE","en")).toBe("Unknown enum (FUTURE_VALUE)");});
  it("has both languages for every field label",()=>{for(const key of Object.keys(fieldTranslationCatalog)){expect(translateField(key,"zh")).not.toContain("未知字段");expect(translateField(key,"en")).not.toContain("Unknown field");}});
  it("translates every order-flow attribution including distinct covering and liquidation",()=>{for(const value of enumManifest.groups.order_flow_attribution)expect(translateEnum("order_flow_attribution",value,"zh")).not.toContain(value);expect(translateEnum("order_flow_attribution","SHORT_COVERING_DOMINANT","zh")).not.toBe(translateEnum("order_flow_attribution","SHORT_LIQUIDATION_ASSISTED","zh"));});
  it.each(["level_role","level_state","level_strength","level_source_type","scenario_type","scenario_direction","scenario_likelihood","scenario_status","position_source","position_status","discipline_warning","audit_failure_code","data_warning"] as EnumGroup[])("fully translates %s",group=>{for(const value of enumManifest.groups[group]){expect(translateEnum(group,value,"zh")).not.toMatch(/^未知枚举/);expect(translateEnum(group,value,"en")).not.toMatch(/^Unknown enum/);}});
  it("keeps safeEnum as an explicit developer-only diagnostic",()=>expect(safeEnum("FUTURE_VALUE")).toBe("UNKNOWN_ENUM(FUTURE_VALUE)"));
});

describe("semantic model in real report components",()=>{
  it.each(semanticKinds)("renders %s with visible glyph, class and ARIA in zh/en",kind=>{for(const language of ["zh","en"] as const){const html=render(<SemanticBadge kind={kind} language={language}/>);expect(html).toContain(`data-semantic-kind=\"${kind}\"`);expect(html).toContain("aria-label=");expect(html).toContain("ama-semantic-glyph");}});
  it("renders AI synthesis, uncertainty and fact inside report sections",()=>{const value={...fixture,report:{...fixture.report!,sections:[{...fixture.report!.sections[0],uncertainties:["Unconfirmed fixture"]}]}};const html=render(<ReportSections value={value} labels={labelsEn} language="en"/>);for(const kind of ["AI_SYNTHESIS","UNCERTAINTY","FACT"])expect(html).toContain(`data-semantic-kind=\"${kind}\"`);});
  it("renders deterministic timeline and timeframe missing-data semantics",()=>{const timeline={...fixture,referenced_facts:[{fact_id:"EVENT_1",category:"EVENT",label:"Event",value:{event_type:"RETEST"},quality:"VALID"}]};expect(render(<Timeline value={timeline} labels={labelsEn} language="en"/>)).toContain("DETERMINISTIC_DERIVATION");expect(render(<TimeframeMatrix value={{...fixture,referenced_facts:[]}} labels={labelsEn} language="en"/>)).toContain("MISSING_DATA");});
  it("renders order-flow counterevidence and gap semantics",()=>{const value={...fixture,referenced_facts:[{fact_id:"FLOW_PHASE_1",value:{primary_attribution:"SHORT_COVERING_DOMINANT",alternative:"SPOT_SELLING_LIKELY",counterevidence:["Opposing CVD"],quality:"PARTIAL",gap_flags:["CVD_GAP"]},quality:"PARTIAL"}]};const html=render(<OrderFlow value={value} labels={labelsEn} language="en"/>);expect(html).toContain("COUNTEREVIDENCE");expect(html).toContain("MISSING_DATA");expect(html).not.toContain("SHORT_COVERING_DOMINANT");});
  it("renders macro fact/derivation and unavailable missing-data",()=>{const full=render(<Macro value={fixture} labels={labelsEn} language="en"/>);expect(full).toContain("FACT");expect(full).toContain("DETERMINISTIC_DERIVATION");expect(render(<Macro value={{...fixture,referenced_macro:[]}} labels={labelsEn} language="en"/>)).toContain("MISSING_DATA");});
  it("renders NONE position as missing and provided fields as facts/derivations",()=>{expect(render(<PositionPanel summary={{source:"NONE"}} details={null} onLoad={()=>{}} labels={labelsEn} language="en"/>)).toContain("MISSING_DATA");const html=render(<PositionPanel summary={{source:"USER_DECLARED"}} details={{average_cost:1900,discipline_warnings:["PLAN_MOSTLY_COMPLETED"]}} onLoad={()=>{}} labels={labelsEn} language="en"/>);expect(html).toContain("FACT");expect(html).toContain("DETERMINISTIC_DERIVATION");expect(html).not.toContain("USER_DECLARED");});
  it("renders audit hard failures as counterevidence",()=>{const value={...fixture,audit_summary:{...fixture.audit_summary!,hard_failure_count:1,hard_failures:["LEVEL_PROJECTION_MISSING"]}};const html=render(<AuditPanel value={value} labels={labelsEn} language="en"/>);expect(html).toContain("COUNTEREVIDENCE");expect(html).toContain("Level projection missing");expect(html).toContain("LEVEL_PROJECTION_MISSING");});
  it("remains distinguishable when color styles are absent",()=>{const html=semanticKinds.map(kind=>render(<SemanticBadge kind={kind} language="en"/>)).join("");for(const kind of semanticKinds){expect(html).toContain(`data-semantic-kind=\"${kind}\"`);}expect((html.match(/ama-semantic-glyph/g)||[]).length).toBe(semanticKinds.length);});
});

describe("field-complete structured panels",()=>{
  it("renders all Key Level fields and state/strength/source cases",()=>{const complete={level_id:"level-complete",zone:[1880,1890],representative_price:1885,asserted_role:"SUPPORT",asserted_state:"FLIPPED",asserted_strength:"MAJOR",timeframes:["1D","1W"],primary_timeframe:"1W",source_types:["PSYCHOLOGICAL_LEVEL","MA20"],asserted_dynamic:true,valid_until:1825030000,slope:1.2,first_detected:1825000000,last_tested:1825010000,broken_at:1825011000,flipped_at:1825012000,invalidation:"Confirmed close",quality:"PARTIAL"};const variants=[complete,{...complete,level_id:"active",asserted_role:"RESISTANCE",asserted_state:"ACTIVE"},{...complete,level_id:"broken",asserted_state:"BROKEN"},{...complete,level_id:"unconfirmed",asserted_state:"UNCONFIRMED"},{...complete,level_id:"weak",asserted_strength:"WEAK",source_types:["PSYCHOLOGICAL_LEVEL"],asserted_dynamic:false}];const html=render(<Levels value={{...fixture,referenced_levels:variants}} labels={labelsEn} language="en"/>);for(const field of enumManifest.groups.level_field)expect(html).toContain(translateField(field,"en"));for(const text of ["Flipped","Active","Broken","Unconfirmed","Major","Weak","Psychological Level","Dynamic position","Static zone"])expect(html).toContain(text);expect(html).toContain("MISSING_DATA");});
  it("renders every Scenario field with localized labels and counterevidence",()=>{const html=render(<Scenarios value={fixture} labels={labelsEn} language="en"/>);for(const field of enumManifest.groups.scenario_field)expect(html).toContain(translateField(field,"en"));expect(html).toContain("COUNTEREVIDENCE");expect(html).not.toMatch(/trigger_text|oi_confirmation_text|funding_basis_confirmation_text/);});
  it("renders Health as five structured groups without raw JSON",()=>{const html=render(<HealthPanel health={fixture.health_summary} labels={labelsEn} language="en"/>);for(const field of enumManifest.groups.health_field)expect(html).toContain(translateField(field,"en"));expect(html).not.toContain("<pre");expect(html).not.toContain("true");expect(html).toContain("Enabled");});
  it("does not leak representative raw business enums in localized panel output",()=>{const html=render(<><ReportSections value={fixture} labels={labelsZh} language="zh"/><Levels value={fixture} labels={labelsZh} language="zh"/><Scenarios value={fixture} labels={labelsZh} language="zh"/><Macro value={fixture} labels={labelsZh} language="zh"/></>);for(const raw of ["POST_BREAKOUT_PULLBACK","AUDIT_PASSED_SHADOW_ONLY","MISSING_DATA","USER_DECLARED","STRONG_BEAR","FAILED_BREAKOUT"])expect(html).not.toContain(`>${raw}<`);});
});
