import { isSafeHttpUrl } from "./types";
import { localizedValue, valueText } from "./formatters";
import { translateEnum, type UiLanguage } from "./enumTranslations";
import { translateField } from "./fieldTranslations";
import { SemanticBadge, SemanticBlock } from "./SemanticBadge";
import type { Presentation } from "./types";
import type { ShadowLabels } from "./i18n";

const factValue = (value: Presentation, category: string) => value.referenced_facts.filter(fact => fact.category === category);
const missingQuality = (value: unknown) => /MISSING|PARTIAL|STALE|UNAVAILABLE|UNKNOWN|GAP/.test(String(value || ""));

export function TimeframeMatrix({ value, labels, language }: { value:Presentation;labels:ShadowLabels;language:UiLanguage }) {
  const rows=["TF15_SUMMARY","TF1H_SUMMARY","TF4H_SUMMARY","TF1D_SUMMARY","TF1W_SUMMARY"].map(id=>value.referenced_facts.find(f=>f.fact_id===id));
  return <section className="ama-panel"><h2>{labels.matrix}</h2><div className="ama-table-scroll" tabIndex={0} role="region" aria-label={labels.matrix}><table><caption>{labels.matrix}</caption><thead><tr><th>{labels.timeframe}</th><th>{labels.matrixFields}</th></tr></thead><tbody>{rows.map((fact,index)=><tr key={index}><th>{["15m","1H","4H","1D","1W"][index]}</th><td><SemanticBadge kind={fact && !missingQuality(fact.quality) ? "DETERMINISTIC_DERIVATION":"MISSING_DATA"} language={language}/><span>{fact ? localizedValue(fact.value,language):labels.empty}</span>{fact?.quality && <small>{translateEnum("data_quality",fact.quality,language)}</small>}</td></tr>)}</tbody></table></div></section>;
}
export function Timeline({ value, labels, language }: { value:Presentation;labels:ShadowLabels;language:UiLanguage }) {
  const events=factValue(value,"EVENT").concat(value.referenced_facts.filter(f=>f.fact_id.startsWith("EVENT_")));
  return <section className="ama-panel"><h2>{labels.timeline}</h2><div className="ama-card-grid">{events.length ? events.map(event=><article key={event.fact_id}><SemanticBadge kind="DETERMINISTIC_DERIVATION" language={language}/><strong>{event.label || event.fact_id}</strong><p>{localizedValue(event.value,language)}</p><small>{[event.timestamp,event.quality && translateEnum("data_quality",event.quality,language)].filter(Boolean).join(" · ")}</small></article>):<SemanticBlock kind="MISSING_DATA" language={language}><p>{labels.empty}</p></SemanticBlock>}</div></section>;
}
export function OrderFlow({ value, labels, language }: { value:Presentation;labels:ShadowLabels;language:UiLanguage }) {
  const phases=value.referenced_facts.filter(f=>f.fact_id.startsWith("FLOW_PHASE"));
  return <section className="ama-panel"><h2>{labels.flow}</h2><div className="ama-card-grid">{phases.map(phase=>{const raw=phase.value && typeof phase.value==="object" ? phase.value as Record<string,unknown>:{}; const attribution=raw.attribution && typeof raw.attribution==="object" ? raw.attribution as Record<string,unknown>:raw; const primary=attribution.primary || raw.primary_attribution || raw.primary_classification; const alternatives=Array.isArray(attribution.alternatives) ? attribution.alternatives : raw.alternative ? [raw.alternative] : raw.alternative_classification ? [raw.alternative_classification]:[]; const counter=Array.isArray(attribution.counterevidence)?attribution.counterevidence:[]; const poor=missingQuality(phase.quality)||missingQuality(raw.quality)||/GAP|PARTIAL/.test(valueText(raw)); return <article key={phase.fact_id}><SemanticBadge kind="DETERMINISTIC_DERIVATION" language={language}/><strong>{phase.label || phase.fact_id}</strong>{Boolean(primary)&&<p><b>{labels.primary}:</b> {translateEnum("order_flow_attribution",primary,language)}</p>}{alternatives.map((item,index)=><p key={index}><SemanticBadge kind={/SELLING|SHORT|LONG_UNWINDING/.test(String(item)) ? "COUNTEREVIDENCE":"UNCERTAINTY"} language={language}/> {translateEnum("alternative_attribution",item,language)}</p>)}{counter.map((item,index)=><p key={index}><SemanticBadge kind="COUNTEREVIDENCE" language={language}/> {String(item)}</p>)}{poor&&<p className="ama-warning"><SemanticBadge kind="MISSING_DATA" language={language}/> {labels.gapPartial}</p>}<dl className="ama-ratios">{["price_change","volume","cvd","oi","funding","basis","liquidation","confidence","quality"].filter(key=>raw[key]!=null).map(key=><div key={key}><dt>{translateField(key,language)}</dt><dd>{localizedValue(raw[key],language)}</dd></div>)}</dl></article>})}</div></section>;
}

const levelFields=["level_id","zone","representative_price","role","state","strength","timeframes","primary_timeframe","source_types","dynamic_static","valid_until","slope","first_detected","last_tested","broken_at","flipped_at","invalidation","quality"] as const;
const levelValue=(level:Record<string,unknown>,field:string) => ({zone:level.zone || [level.zone_low,level.zone_high].filter(x=>x!=null),representative_price:level.representative_price ?? level.price,role:level.asserted_role ?? level.role,state:level.asserted_state ?? level.state,strength:level.asserted_strength ?? level.strength,timeframes:level.timeframes ?? level.asserted_timeframe,primary_timeframe:level.primary_timeframe ?? level.asserted_timeframe,source_types:level.source_types ?? level.source_type,dynamic_static:(level.asserted_dynamic ?? level.dynamic) ? "DYNAMIC":"STATIC",invalidation:level.invalidation ?? level.invalidation_rule}[field] ?? level[field]);
export function Levels({ value, labels, language }: { value:Presentation;labels:ShadowLabels;language:UiLanguage }) {
  return <section className="ama-panel"><h2>{labels.levels}</h2><div className="ama-card-grid">{value.referenced_levels.map((level,index)=>{const role=levelValue(level,"role"),state=levelValue(level,"state"),strength=levelValue(level,"strength"),quality=levelValue(level,"quality");return <article className={`ama-level ama-strength-${String(strength||"UNKNOWN").toLowerCase()}`} key={String(level.level_id||index)}><SemanticBadge kind="DETERMINISTIC_DERIVATION" language={language}/><strong>{translateEnum("level_role",role,language)} · {translateEnum("level_state",state,language)}</strong><p>{String(level.analysis_text||"")}</p>{missingQuality(quality)&&<SemanticBadge kind="MISSING_DATA" language={language}/>}<details><summary>{labels.details}</summary><dl className="ama-ratios">{levelFields.map(field=>{const item=levelValue(level,field); let shown=valueText(item); if(field==="role")shown=translateEnum("level_role",item,language);if(field==="state")shown=translateEnum("level_state",item,language);if(field==="strength")shown=translateEnum("level_strength",item,language);if(field==="source_types")shown=(Array.isArray(item)?item:[item]).filter(Boolean).map(x=>translateEnum("level_source_type",x,language)).join(", ");if(field==="dynamic_static")shown=item==="DYNAMIC"?labels.dynamic:labels.static;if(field==="quality")shown=translateEnum("data_quality",item,language);return <div key={field}><dt>{translateField(field,language)}</dt><dd>{shown}</dd></div>})}</dl></details></article>})}</div></section>;
}

const scenarioFields=["scenario_type","direction","likelihood","status","trigger_text","confirmation_text","expected_path_text","target_level_refs","invalidation_text","invalidation_timeframe","confirmed_close_required","volume_confirmation_text","cvd_confirmation_text","oi_confirmation_text","funding_basis_confirmation_text","contradicting_evidence_text","data_quality","source_references"] as const;
export function Scenarios({ value, labels, language }: { value:Presentation;labels:ShadowLabels;language:UiLanguage }) {
  return <section className="ama-panel"><h2>{labels.scenarios}</h2>{value.referenced_scenarios.map((scenario,index)=><details className="ama-scenario" key={String(scenario.scenario_id||index)}><summary><strong>{translateEnum("scenario_type",scenario.scenario_type,language)}</strong><span>{translateEnum("scenario_direction",scenario.direction,language)} · {translateField("likelihood",language)}：{translateEnum("scenario_likelihood",scenario.likelihood,language)}</span></summary><SemanticBadge kind="DETERMINISTIC_DERIVATION" language={language}/><dl>{scenarioFields.map(field=>{let item=scenario[field]; if(field==="source_references") item=scenario.source_references ?? [...(scenario.fact_refs as unknown[]||[]),...(scenario.level_refs as unknown[]||[]),...(scenario.source_phase_ids as unknown[]||[]),...(scenario.source_event_ids as unknown[]||[])]; let shown=valueText(item); if(field==="scenario_type")shown=translateEnum("scenario_type",item,language);if(field==="direction")shown=translateEnum("scenario_direction",item,language);if(field==="likelihood")shown=translateEnum("scenario_likelihood",item,language);if(field==="status")shown=translateEnum("scenario_status",item,language);if(field==="data_quality")shown=translateEnum("data_quality",item,language);const semantic=field==="likelihood"||field==="status"?"UNCERTAINTY":field==="contradicting_evidence_text"?"COUNTEREVIDENCE":item==null||item===""?"MISSING_DATA":"DETERMINISTIC_DERIVATION";return <div key={field}><dt>{translateField(field,language)}</dt><dd><SemanticBadge kind={semantic} language={language}/> {shown}</dd></div>})}</dl></details>)}</section>;
}
export function Macro({ value, labels, language }: { value:Presentation;labels:ShadowLabels;language:UiLanguage }) {
  return <section className="ama-panel"><h2>{labels.macro}</h2>{value.referenced_macro.length ? value.referenced_macro.map((item,index)=><article key={index}><strong>{String(item.title||item.publisher||labels.evidence)}</strong><p><SemanticBadge kind="FACT" language={language}/> {String(item.factual_summary||"")}</p>{Boolean(item.relevance_reason)&&<p><SemanticBadge kind="DETERMINISTIC_DERIVATION" language={language}/> {String(item.relevance_reason)}</p>}{isSafeHttpUrl(item.url||item.source_url)&&<a href={String(item.url||item.source_url)} target="_blank" rel="noopener noreferrer" aria-label={`${labels.verifiedSource} (${labels.opensTab})`}>{labels.verifiedSource}</a>}</article>):<SemanticBlock kind="MISSING_DATA" language={language}><p>{labels.noMacro}</p></SemanticBlock>}</section>;
}
export function AuditPanel({ value, labels, language }: { value:Presentation;labels:ShadowLabels;language:UiLanguage }) { const audit=value.audit_summary!;return <section className="ama-panel"><h2>{labels.audit}</h2><SemanticBadge kind="DETERMINISTIC_DERIVATION" language={language}/><strong className="ama-score">{audit.overall_score??"—"}</strong><p>{translateEnum("audit_status",audit.status,language)} · {labels.onlyCandidate} · {labels.policy} {audit.policy_version}</p>{audit.hard_failure_count>0&&<div className="ama-critical" role="alert"><SemanticBadge kind="COUNTEREVIDENCE" language={language}/>{labels.hardFailures}: {audit.hard_failure_count}{audit.hard_failures.map(code=><div key={code}>{translateEnum("audit_failure_code",code,language)} <code>{code}</code></div>)}</div>}<dl className="ama-ratios">{Object.entries(audit.ratios||{}).map(([key,val])=><div key={key}><dt>{translateField(key,language)}</dt><dd>{String(val)}</dd></div>)}</dl></section>; }
