import type { UiLanguage } from "./enumTranslations";

const fields = {
  instrument:["交易品种","Instrument"], mode:["报告模式","Report mode"], language:["语言","Language"],
  scenario_type:["路径类型","Scenario type"], direction:["方向","Direction"], likelihood:["证据倾向","Evidence tendency"], status:["状态","Status"], trigger_text:["触发条件","Trigger"], confirmation_text:["确认条件","Confirmation"], expected_path_text:["预期路径","Expected path"], target_level_refs:["目标关键位","Target levels"], invalidation_text:["失效条件","Invalidation"], invalidation_timeframe:["失效周期","Invalidation timeframe"], confirmed_close_required:["要求确认收盘","Confirmed close required"], volume_confirmation_text:["成交量条件","Volume condition"], cvd_confirmation_text:["CVD 条件","CVD condition"], oi_confirmation_text:["OI 条件","OI condition"], funding_basis_confirmation_text:["资金费率 / 基差条件","Funding / basis condition"], contradicting_evidence_text:["反向证据","Counterevidence"], data_quality:["数据质量","Data quality"], source_references:["来源引用","Source references"],
  level_id:["关键位 ID","Level ID"], zone:["价格区域","Zone"], representative_price:["代表价格","Representative price"], role:["角色","Role"], state:["状态","State"], strength:["强度","Strength"], timeframes:["关联周期","Timeframes"], primary_timeframe:["主要周期","Primary timeframe"], source_types:["来源类型","Source types"], dynamic_static:["位置类型","Position type"], valid_until:["有效期至","Valid until"], slope:["斜率","Slope"], first_detected:["首次发现","First detected"], last_tested:["最近测试","Last tested"], broken_at:["破坏时间","Broken at"], flipped_at:["翻转时间","Flipped at"], invalidation:["失效规则","Invalidation"], quality:["质量","Quality"],
  source:["来源","Source"], side:["方向","Side"], average_cost:["平均成本","Average cost"], original_quantity:["原始数量","Original quantity"], remaining_quantity:["剩余数量","Remaining quantity"], original_timeframe:["原始周期","Original timeframe"], original_stop:["原始止损","Original stop"], original_targets:["原始目标","Original targets"], targets_completed:["已完成目标","Targets completed"], discipline_warnings:["纪律警告","Discipline warnings"], plan_completed:["计划已完成","Plan completed"], plan_completion_ratio:["计划完成度","Plan completion ratio"], original_thesis:["原始逻辑","Original thesis"],
  report_version:["报告版本","Report version"], prompt_version:["Prompt 版本","Prompt version"], provider_model:["Provider / 模型","Provider / model"], context_id:["Context ID","Context ID"], registry_snapshot_id:["Registry Snapshot ID","Registry Snapshot ID"], audit_version:["审计版本","Audit version"], policy_version:["Policy 版本","Policy version"], source_versions:["来源版本","Source versions"], presentation_hash:["Presentation 哈希","Presentation hash"],
  reports_enabled:["报告功能","Reports"], shadow_only:["仅 Shadow","Shadow only"], worker_enabled:["报告 Worker","Report worker"], audit_enabled:["审计功能","Audit"], provider_configured:["Provider 配置","Provider configured"], live_provider_allowed:["真实 Provider","Live provider"], queue_depth:["队列深度","Queue depth"], active_requests:["活跃请求","Active requests"], oldest_queued_age:["最早排队时长","Oldest queued age"], last_report_success:["最近报告成功","Last report success"], last_audit_success:["最近审计成功","Last audit success"], failed_count:["失败数量","Failed count"], budget_blocked:["预算阻断","Budget blocked"], daily_tokens:["每日 Token","Daily tokens"], db_size:["数据库大小","Database size"], schema_versions:["Schema 版本","Schema versions"],
  numeric_grounding:["数值依据","Numeric grounding"], reference_support:["引用支持","Reference support"], level_field_coverage:["关键位字段覆盖","Level field coverage"], scenario_field_coverage:["Scenario 字段覆盖","Scenario field coverage"], invalidation_coverage:["失效条件覆盖","Invalidation coverage"], warning_coverage:["警告覆盖","Warning coverage"], contradiction_freedom:["无矛盾比例","Contradiction freedom"], scenario_completeness:["Scenario 完整度","Scenario completeness"], repetition_specificity:["重复与具体性","Repetition / specificity"], position_macro_safety:["持仓与宏观安全","Position / macro safety"],
  price_change:["价格变化","Price change"], volume:["成交量","Volume"], cvd:["CVD","CVD"], oi:["OI","OI"], funding:["资金费率","Funding"], basis:["基差","Basis"], liquidation:["清算","Liquidation"], confidence:["置信度","Confidence"],
} as const;
export type FieldName = keyof typeof fields;
export function translateField(field: string, language: UiLanguage): string { const pair=fields[field as FieldName]; return pair ? pair[language === "zh" ? 0 : 1] : language === "zh" ? `未知字段（${field}）` : `Unknown field (${field})`; }
export const fieldTranslationCatalog = fields;
