import type { Language } from "../i18n";

const copy = {
  en: {
    title:"AI Market Analysis", shadow:"SHADOW ONLY", token:"Admin token", authorize:"Open shadow report", refresh:"Refresh", loading:"Loading audited presentation", error:"Presentation unavailable", facts:"Data facts", derivation:"Program derivation", synthesis:"AI synthesis", uncertainty:"Unconfirmed", counter:"Counterevidence", missing:"Missing data", evidence:"View evidence", warnings:"Data warnings", audit:"Audit scorecard", provenance:"Provenance", health:"Operations health", timeline:"Market timeline", matrix:"Timeframe matrix", flow:"Order flow phases", levels:"Key levels", scenarios:"Scenario tree", position:"Position context", macro:"Macro evidence", noMacro:"No verified macro evidence was included.", noPosition:"No position information was provided.", sensitive:"Show position details", newest:"Latest generated status", displayed:"Latest displayable audited report", staleOld:"This is an older audited report; a newer report is awaiting or failed audit.", disabled:"Shadow market analysis is disabled.", back:"Back to dashboard", current:"Current", aging:"Aging", stale:"Stale", superseded:"Superseded", unknown:"Unknown", pending:"Waiting for audit", failed:"Audit failed", auditError:"Audit system error", notFound:"Audit not created", upgrade:"Schema upgrade required", onlyCandidate:"Audited · Shadow candidate only", instrument:"Instrument", mode:"Report mode", report:"Report", request:"Request", hardFailures:"Hard failures", policy:"Policy", score:"Overall score", promotion:"Promotion eligibility", enabled:"Enabled", disabledValue:"Disabled", feature:"Feature status", queue:"Queue", outcomes:"Outcomes", resources:"Resources", versions:"Versions", dynamic:"Dynamic position", static:"Static zone", verifiedSource:"Verified source", opensTab:"opens in a new tab", reportVersion:"Report version", reportId:"Report ID", contextId:"Context ID", auditId:"Audit ID", decisionTime:"Decision time", marketTime:"Latest confirmed market time", phase:"Market phase", bias:"Directional bias", confidence:"Confidence", quality:"Data quality", timeframe:"Timeframe", matrixFields:"Trend, structure, close, moving averages, momentum, volume, levels, invalidation and quality", empty:"No data available", active:"Active", inactive:"Inactive", shadowCandidate:"AI-6A Shadow candidate", neverProduction:"Not production ready", sensitiveCollapsed:"Sensitive quantities are collapsed by default", details:"Details", alternative:"Alternative attribution", primary:"Primary attribution", counterevidence:"Counterevidence", gapPartial:"Gap or partial data", macroRelevance:"Relevance reason", factualSummary:"Factual summary", publisher:"Publisher", sourceType:"Source type", publishedAt:"Published at", eventTime:"Event time", auditPassed:"PASSED", yes:"Yes", no:"No"
  },
  zh: {
    title:"AI 专业盘面分析", shadow:"仅 SHADOW", token:"管理员令牌", authorize:"打开 Shadow 报告", refresh:"刷新", loading:"正在加载已审计展示快照", error:"展示快照不可用", facts:"数据事实", derivation:"程序推导", synthesis:"AI 综合", uncertainty:"未确认", counter:"反向证据", missing:"数据缺失", evidence:"查看证据", warnings:"数据警告", audit:"审计评分卡", provenance:"来源与版本", health:"运行健康", timeline:"市场过程", matrix:"周期矩阵", flow:"订单流阶段", levels:"关键位", scenarios:"Scenario 路径", position:"持仓上下文", macro:"宏观证据", noMacro:"本次未加入已验证宏观证据。", noPosition:"未提供持仓信息。", sensitive:"显示持仓细节", newest:"最新生成状态", displayed:"当前可展示的最新已审计报告", staleOld:"这是旧的已审计报告；更新报告仍在审计或未通过。", disabled:"Shadow 盘面分析功能未启用。", back:"返回默认看板", current:"当前", aging:"正在变旧", stale:"已过期", superseded:"已被更新报告替代", unknown:"无法判断", pending:"正在等待审计", failed:"审计未通过", auditError:"审计系统错误", notFound:"尚未创建审计", upgrade:"旧 Schema 需要升级", onlyCandidate:"已审计 · 仅 Shadow 候选", instrument:"交易品种", mode:"报告模式", report:"报告", request:"请求", hardFailures:"硬失败", policy:"Policy", score:"总分", promotion:"晋级资格", enabled:"已启用", disabledValue:"未启用", feature:"功能状态", queue:"队列", outcomes:"运行结果", resources:"资源", versions:"版本", dynamic:"动态位置", static:"静态区域", verifiedSource:"已验证来源", opensTab:"在新标签页打开", reportVersion:"报告版本", reportId:"报告 ID", contextId:"Context ID", auditId:"审计 ID", decisionTime:"决策时间", marketTime:"最新确认市场时间", phase:"市场阶段", bias:"方向判断", confidence:"置信度", quality:"数据质量", timeframe:"周期", matrixFields:"趋势、结构、确认收盘、均线、动量、成交量、关键位、失效与质量", empty:"暂无数据", active:"有效", inactive:"无效", shadowCandidate:"AI-6A Shadow 候选", neverProduction:"尚未达到生产就绪", sensitiveCollapsed:"敏感数量默认折叠", details:"详情", alternative:"替代归因", primary:"主要归因", counterevidence:"反向证据", gapPartial:"缺口或部分数据", macroRelevance:"相关性说明", factualSummary:"事实摘要", publisher:"发布方", sourceType:"来源类型", publishedAt:"发布时间", eventTime:"事件时间", auditPassed:"通过", yes:"是", no:"否"
  },
} as const;
export type ShadowLabels = typeof copy.en | typeof copy.zh;
export function shadowText(language: Language): ShadowLabels { return copy[language]; }
