"""Canonical technical safety limits for AI report provider execution."""
from __future__ import annotations


REQUEST_INPUT_TOKEN_MAX = 500_000
PER_CALL_OUTPUT_HARD_CAP = 200_000
OUTPUT_TOKEN_LIMITS = {
    "QUICK": PER_CALL_OUTPUT_HARD_CAP,
    "FULL": PER_CALL_OUTPUT_HARD_CAP,
    "POSITION_AWARE": PER_CALL_OUTPUT_HARD_CAP,
}
PROVIDER_CONTEXT_TOKEN_MAX = 1_000_000
PROVIDER_RESPONSE_BYTES_MAX = 8_000_000
PROVIDER_TIMEOUT_SECONDS = 300
DAILY_INPUT_TOKEN_SAFETY_CAP = 500_000
DAILY_OUTPUT_TOKEN_SAFETY_CAP = 1_000_000
DAILY_TOTAL_TOKEN_SAFETY_CAP = DAILY_INPUT_TOKEN_SAFETY_CAP + DAILY_OUTPUT_TOKEN_SAFETY_CAP
LIVE_PROVIDER_CALLS_PER_24H = 15
B3_MAX_PAID_ATTEMPTS_TOTAL = 15
B3_MAX_SUCCESSFUL_SMOKE_CALLS = 5
