"""Canonical technical safety limits for AI report provider execution."""
from __future__ import annotations


REQUEST_INPUT_TOKEN_MAX = 12_000
OUTPUT_TOKEN_LIMITS = {
    "QUICK": 3_000,
    "FULL": 8_000,
    "POSITION_AWARE": 8_000,
}
DAILY_INPUT_TOKEN_SAFETY_CAP = 150_000
DAILY_OUTPUT_TOKEN_SAFETY_CAP = 80_000
DAILY_TOTAL_TOKEN_SAFETY_CAP = DAILY_INPUT_TOKEN_SAFETY_CAP + DAILY_OUTPUT_TOKEN_SAFETY_CAP
LIVE_PROVIDER_CALLS_PER_24H = 10
B3_MAX_PAID_ATTEMPTS_TOTAL = 9
B3_MAX_SUCCESSFUL_SMOKE_CALLS = 5
