"""Stable contracts for deterministic AI-5 report auditing."""
from __future__ import annotations

from enum import Enum


class ClaimType(str, Enum):
    MARKET_PHASE="MARKET_PHASE"; PRICE_STRUCTURE="PRICE_STRUCTURE"; TIMEFRAME_TREND="TIMEFRAME_TREND"
    MOMENTUM="MOMENTUM"; VOLUME="VOLUME"; CVD="CVD"; OPEN_INTEREST="OPEN_INTEREST"
    FUNDING="FUNDING"; BASIS="BASIS"; LIQUIDATION="LIQUIDATION"; ORDER_FLOW_ATTRIBUTION="ORDER_FLOW_ATTRIBUTION"
    KEY_LEVEL="KEY_LEVEL"; SCENARIO="SCENARIO"; INVALIDATION="INVALIDATION"; POSITION="POSITION"
    POSITION_DISCIPLINE="POSITION_DISCIPLINE"; MACRO="MACRO"; DATA_QUALITY="DATA_QUALITY"
    LIMITATION="LIMITATION"; INFERENCE="INFERENCE"; UNCERTAINTY="UNCERTAINTY"; SAFETY="SAFETY"; OTHER="OTHER"


class Modality(str, Enum):
    FACT="FACT"; DETERMINISTIC_DERIVATION="DETERMINISTIC_DERIVATION"; LIKELY="LIKELY"
    POSSIBLE="POSSIBLE"; UNCERTAIN="UNCERTAIN"; CONDITIONAL="CONDITIONAL"; CONFIRMED="CONFIRMED"
    UNKNOWN="UNKNOWN"; NOT_AVAILABLE="NOT_AVAILABLE"


class AuditStatus(str, Enum):
    PASSED="PASSED"; FAILED="FAILED"; ERROR="ERROR"


HARD_FAILURE_CODES = (
    "AUDIT_INPUT_INCOMPLETE","REPORT_HASH_MISMATCH","CONTEXT_HASH_MISMATCH","SOURCE_VERSION_MISMATCH",
    "INSTRUMENT_MISMATCH","TIMEFRAME_MISMATCH","UNKNOWN_REFERENCE","REFERENCE_NOT_SUPPORTING_CLAIM",
    "NUMERIC_HALLUCINATION","NUMERIC_DIRECTION_MISMATCH","NUMERIC_UNIT_MISMATCH","UNPARSED_NUMERIC_CLAIM",
    "UNSUPPORTED_CLAIM","UNKNOWN_PROMOTED_TO_FACT","LIKELY_PROMOTED_TO_CONFIRMED","CRITICAL_CONTRADICTION",
    "ORDER_FLOW_CONTRADICTION","KEY_LEVEL_CONTRADICTION","SCENARIO_INCOMPLETE","INVALIDATION_MISSING",
    "CRITICAL_WARNING_OMITTED","UNSUPPORTED_POSITION","UNSUPPORTED_MACRO","EXACT_PROBABILITY",
    "ORDER_INSTRUCTION","GUARANTEE_OR_CERTAINTY","SECRET_OR_INTERNAL_DATA_EXPOSURE","REQUIRED_SECTION_MISSING",
    "AUDIT_INTERNAL_ERROR",
)
