import { useEffect,useMemo,useState } from "react";
import { Activity,AlertTriangle,Database,RefreshCw } from "lucide-react";

type Job={id:number;job_type:string;status:string;progress:number;progress_message?:string;queue_position?:number;error?:string;created_at:string;started_at?:string};
type Alert={id:number;alert_type:string;severity:string;status:string;component:string;instrument?:string;message:string;last_seen:string;occurrence_count:number};
type Coverage={instrument:string;timeframe:string;rows:number;first_ts:number;last_ts:number};
type Health={status:string;version:string;git_commit:string;uptime_seconds:number;database_status:string;database_size_bytes:number;database_integrity_status:string;paper_scheduler_running:boolean;last_cycle_completed_at?:string;last_cycle_duration_ms?:number;collector_freshness:Record<string,{updated_at?:string;age_seconds?:number;status:string}>;active_job?:Job;queued_jobs:number;deepseek_configured:boolean;last_ai_success?:string;disk_usage:{percent:number};memory_usage:{percent?:number}};
async function api<T>(path:string,options?:RequestInit):Promise<T>{const response=await fetch(path,options);const body=await response.json();if(!response.ok)throw new Error(body.error||`Request failed: ${response.status}`);return body}
export default function Operations(){
 const [health,setHealth]=useState<Health|null>(null);const [jobs,setJobs]=useState<Job[]>([]);const [alerts,setAlerts]=useState<Alert[]>([]);const [coverage,setCoverage]=useState<Coverage[]>([]);const [error,setError]=useState("");const [adminToken,setAdminToken]=useState(()=>sessionStorage.getItem("crypto_bot_admin_token")||"");
 async function refresh(){try{const [h,j,a,c]=await Promise.all([api<Health>("/api/health/details"),api<{items:Job[]}>("/api/jobs"),api<{items:Alert[]}>("/api/alerts"),api<{items:Coverage[]}>("/api/data-coverage")]);setHealth(h);setJobs(j.items);setAlerts(a.items);setCoverage(c.items);setError("")}catch(e){setError(e instanceof Error?e.message:"Operations API unavailable")}}
 useEffect(()=>{refresh();const timer=setInterval(refresh,5000);return()=>clearInterval(timer)},[]);
 const open=useMemo(()=>alerts.filter(a=>a.status==="open"),[alerts]);const headers=():Record<string,string>=>{const token=sessionStorage.getItem("crypto_bot_admin_token");return token?{Authorization:`Bearer ${token}`}:{}};
 async function action(path:string){try{await api(path,{method:"POST",headers:{...headers(),"Content-Type":"application/json"},body:"{}"});await refresh()}catch(e){setError(e instanceof Error?e.message:"Operation failed")}}
 return <main className="operations-workspace"><section className="operations-hero"><div><span className="eyebrow">Production operations · sanitized public status</span><h1>Operations</h1><p>Service health, collectors, persistent research queue and in-app alerts.</p></div><div className="operations-actions"><label>Admin Token<input type="password" value={adminToken} placeholder="Optional · session only" onChange={e=>{setAdminToken(e.target.value);if(e.target.value)sessionStorage.setItem("crypto_bot_admin_token",e.target.value);else sessionStorage.removeItem("crypto_bot_admin_token")}}/></label><button className="secondary-btn" onClick={refresh}><RefreshCw size={14}/> Refresh</button><small>Plain HTTP does not secure token transport.</small></div></section>{error&&<div className="research-alert error">{error}</div>}
 <div className="operations-grid"><section className="operations-card health-overview"><div className="operations-title"><Activity size={17}/><h2>Service Health</h2><span className={`status-pill ${health?.status}`}>{health?.status||"unknown"}</span></div><div className="ops-metrics">{[["Version",health?.version],["Git Commit",health?.git_commit],["Uptime",health?`${Math.floor(health.uptime_seconds/60)} min`:"—"],["Disk",health?`${health.disk_usage.percent}%`:"—"],["Memory",health?.memory_usage.percent!==undefined?`${health.memory_usage.percent}%`:"Unavailable"]].map(([l,v])=><article key={l}><span>{l}</span><b>{v}</b></article>)}</div></section>
 <section className="operations-card"><div className="operations-title"><Activity size={17}/><h2>Collector Freshness</h2></div><div className="collector-list">{Object.entries(health?.collector_freshness||{}).map(([asset,x])=><div key={asset}><b>{asset}</b><span className={`status-pill ${x.status}`}>{x.status}</span><small>{x.age_seconds!==undefined?`${Math.round(x.age_seconds)}s ago`:"No sample"}</small></div>)}</div></section>
 <section className="operations-card"><div className="operations-title"><Database size={17}/><h2>Database Status</h2></div><div className="ops-facts"><span>Status <b>{health?.database_status||"—"}</b></span><span>Integrity <b>{health?.database_integrity_status||"not checked"}</b></span><span>Size <b>{health?`${(health.database_size_bytes/1048576).toFixed(2)} MiB`:"—"}</b></span></div></section>
 <section className="operations-card"><div className="operations-title"><Activity size={17}/><h2>Runtime Status</h2></div><div className="ops-facts"><span>Paper Scheduler <b>{health?.paper_scheduler_running?"Running":"Stopped"}</b></span><span>Last Cycle <b>{health?.last_cycle_completed_at?new Date(health.last_cycle_completed_at).toLocaleString():"—"}</b></span><span>Cycle Duration <b>{health?.last_cycle_duration_ms??"—"} ms</b></span><span>AI <b>{health?.deepseek_configured?"Configured":"Disabled"}</b></span></div></section></div>
 <div className="operations-grid"><section className="operations-card"><div className="operations-title"><Activity size={17}/><h2>Active Job</h2></div>{health?.active_job?<div className="ops-facts"><span>Job <b>#{health.active_job.id} · {health.active_job.job_type}</b></span><span>Progress <b>{health.active_job.progress}%</b></span></div>:<p className="research-empty compact">No heavy research job is running.</p>}</section><section className="operations-card"><div className="operations-title"><Activity size={17}/><h2>Recent Completed Jobs</h2></div><div className="ops-facts">{jobs.filter(j=>["COMPLETED","FAILED","CANCELLED","INTERRUPTED"].includes(j.status)).slice(0,4).map(j=><span key={j.id}>#{j.id} · {j.job_type}<b>{j.status}</b></span>)}</div></section></div>
 <section className="operations-card wide"><div className="operations-title"><Activity size={17}/><h2>Job Queue</h2><span>{health?.queued_jobs||0} queued</span></div><div className="research-table-wrap"><table><thead><tr><th>Job</th><th>Type</th><th>Status</th><th>Queue</th><th>Progress</th><th>Message / Error</th><th>Created</th><th>Action</th></tr></thead><tbody>{jobs.slice(0,30).map(j=><tr key={j.id}><td>#{j.id}</td><td>{j.job_type}</td><td>{j.status}</td><td>{j.queue_position||"—"}</td><td>{j.progress}%</td><td>{j.error||j.progress_message||"—"}</td><td>{new Date(j.created_at).toLocaleString()}</td><td>{["QUEUED","RUNNING"].includes(j.status)&&<button onClick={()=>action(`/api/jobs/${j.id}/cancel`)}>Cancel</button>}{["FAILED","CANCELLED","INTERRUPTED"].includes(j.status)&&<button onClick={()=>action(`/api/jobs/${j.id}/retry`)}>Retry</button>}</td></tr>)}</tbody></table></div></section>
 <section className="operations-card wide"><div className="operations-title"><AlertTriangle size={17}/><h2>Alert Center</h2><span className="alert-count">{open.length} open</span></div><div className="alert-list">{alerts.length?alerts.map(a=><article key={a.id} className={`alert-row ${a.severity}`}><span className={`status-pill ${a.severity}`}>{a.severity}</span><div><b>{a.alert_type}{a.instrument?` · ${a.instrument}`:""}</b><p>{a.message}</p><small>{a.component} · {new Date(a.last_seen).toLocaleString()} · {a.occurrence_count} occurrence(s) · {a.status}</small></div>{a.status==="open"&&<button onClick={()=>action(`/api/alerts/${a.id}/acknowledge`)}>Acknowledge</button>}</article>):<p className="research-empty compact">No alerts recorded.</p>}</div></section>
 <section className="operations-card wide"><div className="operations-title"><Database size={17}/><h2>Data Coverage</h2></div><div className="research-table-wrap"><table><thead><tr><th>Instrument</th><th>Timeframe</th><th>Confirmed Rows</th><th>First Candle</th><th>Last Candle</th></tr></thead><tbody>{coverage.map(x=><tr key={`${x.instrument}-${x.timeframe}`}><td>{x.instrument}</td><td>{x.timeframe}</td><td>{x.rows}</td><td>{new Date(x.first_ts*1000).toLocaleString()}</td><td>{new Date(x.last_ts*1000).toLocaleString()}</td></tr>)}</tbody></table></div></section></main>
}
