import { useEffect,useState } from "react";
import { Play } from "lucide-react";
import { researchApi, type ResearchJob, type StrategyParameters } from "./research";

export default function PortfolioResearch({startDate,endDate,parameters}:{startDate:string;endDate:string;parameters:StrategyParameters}){
 const [assets,setAssets]=useState(["BTC-USDT","ETH-USDT","SOL-USDT"]); const [job,setJob]=useState<ResearchJob|null>(null); const [result,setResult]=useState<Record<string,any>|null>(null); const [error,setError]=useState("");
 useEffect(()=>{if(!job||!["QUEUED","RUNNING"].includes(job.status))return;const timer=setInterval(async()=>{const next=(await researchApi.jobs()).find(x=>x.id===job.id);if(!next)return;setJob(next);if(next.status==="COMPLETED"&&next.result_ref){const ref=JSON.parse(next.result_ref);setResult(await researchApi.portfolioRun(ref.portfolio_run_id));}if(next.status==="FAILED")setError(next.error||"Portfolio job failed.");},1000);return()=>clearInterval(timer)},[job?.id,job?.status]);
 async function run(){setError("");setResult(null);try{setJob(await researchApi.portfolio({assets,start_date:startDate,end_date:endDate,parameters,initial_capital:parameters.initial_capital,max_positions:3,max_asset_weight:.5,max_asset_risk:.015,max_portfolio_risk:.03,max_long_exposure:1,max_short_exposure:1,asset_weights:Object.fromEntries(assets.map(a=>[a,1/assets.length]))}))}catch(e){setError(e instanceof Error?e.message:"Portfolio could not start.")}}
 const metrics=result?.result?.metrics;
 return <section className="research-panel"><div className="research-panel-head"><div><span className="eyebrow">Shared cash · chronological event stream</span><h2>Portfolio Backtest</h2></div><button className="primary-btn" onClick={run} disabled={!assets.length||!!job&&["QUEUED","RUNNING"].includes(job.status)}><Play size={14}/> Run Portfolio</button></div><div className="portfolio-assets">{["BTC-USDT","ETH-USDT","SOL-USDT"].map(a=><label key={a}><input type="checkbox" checked={assets.includes(a)} onChange={e=>setAssets(v=>e.target.checked?[...v,a]:v.filter(x=>x!==a))}/>{a}</label>)}</div>{job&&<div className="research-progress"><div><span>{job.progress_message||job.status}{job.queue_position?` · queue #${job.queue_position}`:""}</span><b>{job.progress}%</b></div><i><span style={{width:`${job.progress}%`}}/></i></div>}{error&&<div className="research-alert error">{error}</div>}{metrics&&<><div className="research-metrics">{[["Portfolio Return",metrics.total_return,"%"],["Maximum Drawdown",metrics.maximum_drawdown,"%"],["Sharpe",metrics.sharpe_ratio,""],["Total Trades",metrics.total_trades,""],["Exposure",metrics.exposure,"%"],["Cash Utilization",metrics.cash_utilization,"%"],["Long Exposure",metrics.long_exposure,"%"],["Short Exposure",metrics.short_exposure,"%"],["Concurrent Positions",metrics.concurrent_positions,""]].map(([l,v,s])=><article key={String(l)}><span>{l}</span><strong>{typeof v==="number"?`${v.toFixed(2)}${s}`:"Insufficient Data"}</strong></article>)}</div><div className="research-table-wrap"><table><thead><tr><th>Asset</th><th>P&amp;L</th><th>Contribution</th><th>Fees</th></tr></thead><tbody>{assets.map(a=><tr key={a}><td>{a}</td><td>{metrics.per_asset_pnl?.[a]?.toFixed(2)??"0.00"}</td><td>{metrics.per_asset_contribution?.[a]?.toFixed(2)??"0.00"}%</td><td>{metrics.fees_by_asset?.[a]?.toFixed(2)??"0.00"}</td></tr>)}</tbody></table></div><small className="method-note">{result?.result?.execution_model}</small></>}</section>
}
