import { useEffect, useMemo, useState } from "react";
import { RefreshCw } from "lucide-react";
import "./PredictionMarkets.css";

const apiBase = (window.__PAPER_API_URL__ || import.meta.env.VITE_PAPER_API_URL || "").replace(/\/$/, "");
const copy = { research: "Prediction Markets Research", markets: "Markets", marketDetail: "Market detail", forecasts: "Forecasts", forecastDetail: "Forecast audit detail", scoreboard: "Scoreboard", searchMarkets: "Search prediction markets", search: "Search markets", filter: "Market filter", close: "Close detail" };
const accessibility = copy;
type Row = Record<string, unknown>;
const val = (row: Row | undefined, ...names: string[]) => names.map((name) => row?.[name]).find((value) => value !== undefined && value !== null);
const text = (row: Row | undefined, ...names: string[]) => String(val(row, ...names) ?? "—");
const number = (row: Row | undefined, ...names: string[]) => { const n = Number(val(row, ...names)); return Number.isFinite(n) ? n : undefined; };
const percent = (n: unknown) => { const value = Number(n); return Number.isFinite(value) ? `${(Math.abs(value) <= 1 ? value * 100 : value).toFixed(1)}%` : "Unavailable"; };
const date = (value: unknown) => value ? new Date(String(value)).toLocaleString() : "—";

function rows(payload: Row | undefined) { const candidate = val(payload, "items", "markets", "forecasts", "cohorts"); return Array.isArray(candidate) ? candidate as Row[] : []; }
function useDebounced(value: string, delay = 300) { const [debounced, setDebounced] = useState(value); useEffect(() => { const timer = window.setTimeout(() => setDebounced(value), delay); return () => window.clearTimeout(timer); }, [value, delay]); return debounced; }

function Resource({ path, children }: { path: string; children: (data: Row | undefined, loading: boolean, error: string | undefined, refresh: () => void) => React.ReactNode }) {
  const [data, setData] = useState<Row>(); const [error, setError] = useState<string>(); const [loading, setLoading] = useState(true); const [refreshKey, setRefreshKey] = useState(0);
  const refresh = () => setRefreshKey((key) => key + 1);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(undefined); fetch(`${apiBase}/api/polymarket${path}`, { cache: "no-store", signal: controller.signal }).then((response) => { if (!response.ok) throw new Error(`HTTP_${response.status}`); return response.json() as Promise<Row>; }).then(setData).catch((e: Error) => { if (e.name !== "AbortError") setError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [path, refreshKey]);
  return <>{children(data, loading, error, refresh)}</>;
}
function State({ loading, error, retry, children }: { loading: boolean; error?: string; retry?: () => void; children: React.ReactNode }) { if (loading) return <div className="pm-state" role="status">Loading research data…</div>; if (error) return <div className="pm-state error" role="alert"><span>Prediction Markets API unavailable ({error}).</span>{retry && <button className="secondary-btn" onClick={retry}>Try again</button>}</div>; return <>{children}</>; }
function Metric({ label, value, detail }: { label: string; value: string; detail?: string }) { return <article className="pm-metric"><span>{label}</span><b>{value}</b>{detail && <small>{detail}</small>}</article>; }
function PageHeader({ title, children }: { title: string; children: React.ReactNode }) { return <header className="pm-header"><div><span className="eyebrow">PREDICTION MARKETS RESEARCH</span><h1>{title}</h1><p>Independent AI forecasts benchmarked against market probabilities.</p></div>{children}</header>; }

function Overview({ navigate }: { navigate: (view: "overview" | "markets" | "forecasts" | "scoreboard") => void }) { return <Resource path="/overview">{(data, loading, error, refresh) => <main className="prediction-markets"><PageHeader title={copy.research}><button className="secondary-btn" onClick={refresh}><RefreshCw size={14}/> Refresh</button></PageHeader><State loading={loading} error={error} retry={refresh}><section className="pm-metrics">
  <Metric label="Markets tracked" value={text(data, "active_universe_count", "universe_count", "markets_tracked")} /> <Metric label="Eligible" value={text(data, "eligible_markets", "eligible_count")} /> <Metric label="AI forecasts" value={text(data, "llm_forecasts", "total_llm_forecasts", "forecast_count")} detail={`${text(data, "unresolved_forecasts", "unresolved")} awaiting resolution`} /> <Metric label="Resolved" value={text(data, "resolved_forecasts", "resolved")} />
  <Metric label="Model vs Market" value={number(data, "scored_count", "scored") ? percent(number(data, "delta_brier", "model_vs_market_brier_delta")) : "Awaiting resolutions"} detail={number(data, "scored_count", "scored") ? "Brier delta" : "Performance is unavailable until outcomes are known"} />
  </section><section className="pm-panel"><span className="eyebrow">RESEARCH PIPELINE</span><div className="pm-pipeline">{["Market", "Evidence", "Independent Forecast", "Immutable Commit", "Market Reveal", "Resolution", "Scoring"].map((step) => <span key={step}>{step}</span>)}</div><p>AI evidence review and the immutable forecast commit are separated from market-price reveal.</p></section><Latest onNavigate={navigate}/></State></main>}</Resource>; }
function Latest({ onNavigate }: { onNavigate: (view: "overview" | "markets" | "forecasts" | "scoreboard") => void }) { const [selected, setSelected] = useState<string>(); return <Resource path="/forecasts?limit=8">{(data, loading, error, refresh) => <section className="pm-panel"><div className="pm-panel-title"><div><span className="eyebrow">RECENT RESEARCH</span><h2>Latest Forecasts</h2></div><button className="secondary-btn" onClick={() => onNavigate("forecasts")}>View forecasts</button></div><State loading={loading} error={error} retry={refresh}>{rows(data).length ? <div className="pm-list">{rows(data).slice(0, 8).map((item) => { const id = text(item, "forecast_id", "id"); return <button type="button" key={id} title={text(item, "market_question", "question")} onClick={() => setSelected(id)}><b>{text(item, "market_question", "question")}</b><span>AI {percent(val(item, "ai_probability", "probability"))} · Market {percent(val(item, "market_probability_at_commit", "market_probability"))}</span><small>{text(item, "resolution_status", "status")}</small></button>; })}</div> : <p className="pm-empty">No committed forecasts yet.</p>}</State>{selected && <DetailRecord title={copy.forecastDetail} path={`/forecasts/${encodeURIComponent(selected)}`} close={() => setSelected(undefined)}/>}</section>}</Resource>; }

function Markets() { const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const debouncedQuery = useDebounced(query); const path = useMemo(() => `/markets?limit=50${debouncedQuery ? `&search=${encodeURIComponent(debouncedQuery)}` : ""}${filter !== "all" ? `&${filter}=true` : ""}`, [debouncedQuery, filter]); return <Resource path={path}>{(data, loading, error, refresh) => <main className="prediction-markets"><PageHeader title={copy.markets}><span/></PageHeader><div className="pm-controls"><input aria-label={copy.searchMarkets} placeholder={copy.search} value={query} onChange={(e) => setQuery(e.target.value)}/><select aria-label={copy.filter} value={filter} onChange={(e) => setFilter(e.target.value)}><option value="all">All</option><option value="eligible">Eligible</option><option value="forecasted">Forecasted</option><option value="unresolved">Awaiting evidence / resolution</option><option value="resolved">Resolved</option></select></div><State loading={loading} error={error} retry={refresh}><MarketTable items={rows(data)}/></State></main>}</Resource>; }
function MarketTable({ items }: { items: Row[] }) { const [selected, setSelected] = useState<string>(); return <><div className="pm-table-wrap"><table className="pm-table"><thead><tr><th>Question</th><th>Event</th><th>End date</th><th>Market probability</th><th>Eligibility</th><th>Forecast</th><th>Resolution</th></tr></thead><tbody>{items.map((item) => { const id = text(item, "market_id", "id"); const open = () => setSelected(id); return <tr key={id} tabIndex={0} onClick={open} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") open(); }}><td title={text(item, "question", "market_question")}>{text(item, "question", "market_question")}</td><td>{text(item, "event", "event_title")}</td><td>{date(val(item, "end_date", "endDate"))}</td><td>{percent(val(item, "yes_midpoint", "market_probability"))}</td><td><span className="pm-chip">{text(item, "eligibility", "eligibility_status")}</span></td><td>{text(item, "forecast_status")}</td><td>{text(item, "resolution_status")}</td></tr>; })}</tbody></table></div>{!items.length && <p className="pm-empty">No markets match the current filters.</p>}{selected && <DetailRecord title={copy.marketDetail} path={`/markets/${encodeURIComponent(selected)}`} close={() => setSelected(undefined)}/>}</>; }

function Forecasts() { return <Resource path="/forecasts?limit=50">{(data, loading, error, refresh) => <main className="prediction-markets"><PageHeader title={copy.forecasts}><span/></PageHeader><State loading={loading} error={error} retry={refresh}><ForecastTable items={rows(data)}/></State></main>}</Resource>; }
function ForecastTable({ items }: { items: Row[] }) { const [selected, setSelected] = useState<string>(); return <><div className="pm-table-wrap"><table className="pm-table"><thead><tr><th>Question</th><th>AI %</th><th>Market %</th><th>Edge</th><th>Confidence</th><th>Evidence</th><th>Committed</th><th>Status</th></tr></thead><tbody>{items.map((item) => { const id = text(item, "forecast_id", "id"); const open = () => setSelected(id); return <tr key={id} tabIndex={0} onClick={open} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") open(); }}><td title={text(item, "market_question", "question")}>{text(item, "market_question", "question")}</td><td>{percent(val(item, "ai_probability", "probability"))}</td><td>{percent(val(item, "market_probability_at_commit", "market_probability"))}</td><td>{percent(val(item, "residual", "edge"))}</td><td>{text(item, "confidence")}</td><td>{text(item, "evidence_count")}</td><td>{date(val(item, "committed_at", "created_at"))}</td><td>{text(item, "resolution_status", "status")}</td></tr>; })}</tbody></table></div>{!items.length && <p className="pm-empty">No committed forecasts yet.</p>}{selected && <DetailRecord title={copy.forecastDetail} path={`/forecasts/${encodeURIComponent(selected)}`} close={() => setSelected(undefined)}/>}</>; }
const asRow = (value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? value as Row : undefined;
function DetailRecord({ title, path, close }: { title: string; path: string; close: () => void }) { return <Resource path={path}>{(data, loading, error, refresh) => <div className="pm-backdrop" onClick={close}><section className="pm-detail" role="dialog" aria-modal="true" aria-label={title} onClick={(event) => event.stopPropagation()}><button className="icon-button" aria-label={accessibility.close} onClick={close}>×</button><State loading={loading} error={error} retry={refresh}>{data && <Detail title={title} item={data}/>}</State></section></div>}</Resource>; }
function Detail({ title, item }: { title: string; item: Row }) { const embedded = asRow(val(item, "forecast")); const record = asRow(val(embedded, "forecast")) || embedded || item; const snapshot = asRow(val(embedded, "frozen_market_snapshot")) || asRow(val(item, "market_snapshot")); const audit = asRow(val(embedded, "audit")) || asRow(val(item, "audit")); const methodology = asRow(val(embedded, "methodology")) || asRow(val(item, "methodology")); const resolution = asRow(val(embedded, "resolution")) || asRow(val(item, "resolution")); const evidence = val(embedded, "evidence"); const evidenceCount = Array.isArray(evidence) ? String(evidence.length) : text(record, "evidence_count"); return <><span className="eyebrow">IMMUTABLE RESEARCH RECORD</span><h2>{title}</h2><h3 title={text(embedded || item, "question", "market_question")}>{text(embedded || item, "question", "market_question")}</h3><div className="pm-detail-grid">{[["AI probability", percent(val(record,"ai_probability","probability"))], ["Market at commit", percent(val(record,"market_probability","market_probability_at_commit") ?? val(snapshot,"yes_midpoint"))], ["Residual", percent(val(record,"residual","edge"))], ["Confidence", text(embedded || record,"confidence")], ["Evidence", evidenceCount], ["Committed", date(val(embedded || record,"committed_at","created_at"))], ["Methodology", text(methodology,"forecast_schema_version","prompt_version")], ["Resolution", text(resolution,"status","classification")], ["Forecast hash", text(audit,"forecast_hash","commit_hash")]].map(([label, value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</div><p className="pm-empty">Detailed evidence references and frozen snapshot lineage are available through this read-only immutable record.</p></>; }

function Scoreboard() { return <Resource path="/scoreboard">{(data, loading, error, refresh) => { const performance = val(data, "performance") as Row | undefined; const scored = number(performance, "scored_count"); return <main className="prediction-markets"><PageHeader title={copy.scoreboard}><span/></PageHeader><State loading={loading} error={error} retry={refresh}>{!scored ? <section className="pm-empty-state"><h2>No forecasts have resolved yet.</h2><p>Performance statistics will appear after outcomes are known.</p><b>{text(data, "unresolved_forecasts", "unresolved")} unresolved forecasts</b></section> : <section className="pm-metrics"><Metric label="Scored" value={text(performance,"scored_count")}/><Metric label="Model Brier" value={text(performance,"mean_brier_model")}/><Metric label="Market Brier" value={text(performance,"mean_brier_market")}/><Metric label="Delta" value={text(performance,"mean_delta_brier")}/></section>}<section className="pm-panel"><span className="eyebrow">SAMPLE INTEGRITY</span><div className="pm-integrity"><Metric label="Raw forecasts" value={text(performance,"raw_resolved_forecasts")}/><Metric label="Unique event clusters" value={text(performance,"unique_statistical_clusters")}/><Metric label="Resolved" value={text(performance,"raw_resolved_forecasts")}/><Metric label="Scored" value={text(performance,"scored_count")}/></div><p>{!scored ? "Performance is unavailable until forecasts resolve." : text(data, "sample_warning", "warning") !== "—" ? "The resolved sample is still too small for reliable conclusions." : "Statistics are presented only when the resolved sample is sufficient."}</p></section></State></main>; }}</Resource>; }

export default function PredictionMarkets({ view, navigate }: { view: "overview" | "markets" | "forecasts" | "scoreboard"; navigate: (view: "overview" | "markets" | "forecasts" | "scoreboard") => void }) { const page = view === "markets" ? <Markets/> : view === "forecasts" ? <Forecasts/> : view === "scoreboard" ? <Scoreboard/> : <Overview navigate={navigate}/>; return <><nav className="pm-nav" aria-label={copy.research}><div>{(["overview", "markets", "forecasts", "scoreboard"] as const).map((destination) => <button key={destination} className={view === destination ? "active" : ""} aria-current={view === destination ? "page" : undefined} onClick={() => navigate(destination)}>{destination === "overview" ? "Overview" : copy[destination]}</button>)}</div></nav>{page}</>; }
