import { useMemo, useState } from "react";
import type { Reconciliation } from "./research";

export default function ReconciliationPanel({ data }:{data:Reconciliation|null}) {
  const [filter,setFilter]=useState("ALL");
  const items=useMemo(()=>data?.items.filter(item=>filter==="ALL"||filter==="MATCHED"&&item.match_status==="Exact Match"||filter==="UNMATCHED"&&item.match_status!=="Exact Match"||item.match_status===filter)||[],[data,filter]);
  if(!data)return <div className="research-empty compact">A completed run is required. No matches are synthesized.</div>;
  return <><div className="drift-head"><span className={`drift ${data.drift_status.toLowerCase().replace(" ","-")}`}>Strategy Drift · {data.drift_status}</span><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All Lineage</option><option value="MATCHED">Matched</option><option value="UNMATCHED">Unmatched / Divergent</option>{["Decision Mismatch","Paper Missing","Backtest Missing","Entry Divergence","Exit Divergence","Risk Blocked","Service Gap","Legacy Unmatched"].map(x=><option key={x}>{x}</option>)}</select></div><div className="reconciliation-grid">{[["Signal Match",data.signal_match_rate],["Action Mismatch",data.action_mismatch_rate],["Median Entry Difference",data.median_entry_difference_pct],["Unmatched Ratio",data.unmatched_signal_ratio]].map(([label,value])=><article key={String(label)}><span>{label}</span><b>{typeof value==="number"?`${value.toFixed(2)}%`:"Insufficient Data"}</b></article>)}</div><div className="research-table-wrap"><table><thead><tr>{["Signal ID","Instrument","Candle Close","Paper / Backtest","Scores","Expected / Observed Entry","Entry Difference","Paper / Backtest Exit","Result R","Status"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{items.map((x,i)=><tr key={`${x.signal_id||"legacy"}-${i}`}><td title={x.signal_id}>{x.signal_id?x.signal_id.slice(0,12):"Legacy / none"}</td><td>{x.instrument}</td><td>{x.candle_close_ts?new Date(x.candle_close_ts*1000).toLocaleString():"—"}</td><td>{x.paper_action||"—"} / {x.backtest_action||"—"}</td><td>{x.paper_score??"—"} / {x.backtest_score??"—"}</td><td>{x.expected_entry_price?.toFixed(4)??"—"} / {x.observed_entry_price?.toFixed(4)??"—"}</td><td>{x.entry_difference_pct!==undefined?`${x.entry_difference_pct.toFixed(3)}%`:"—"}</td><td>{x.paper_exit_reason||"—"} / {x.backtest_exit_reason||"—"}</td><td>{x.paper_result_r?.toFixed(2)??"—"} / {x.backtest_result_r?.toFixed(2)??"—"}</td><td>{x.match_status}</td></tr>)}</tbody></table></div></>;
}
