"""Generate the deterministic Shadow UI enum manifest and TypeScript mirror."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from dashboard.ai_market_analysis.ui_enum_manifest import UI_ENUM_GROUPS, UI_ENUM_MANIFEST_VERSION


def payload() -> dict[str, object]:
    return {"version": UI_ENUM_MANIFEST_VERSION, "groups": {key: list(values) for key, values in sorted(UI_ENUM_GROUPS.items())}}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = ROOT
    json_path = root / "schemas/ai_market_analysis/ai_market_ui_enum_manifest_v1.json"
    ts_path = root / "frontend/src/aiMarketAnalysis/enumManifest.generated.ts"
    body = json.dumps(payload(), ensure_ascii=False, sort_keys=True, indent=2) + "\n"
    ts = "// Generated by scripts/generate_ai_market_ui_enum_manifest.py; do not edit.\n" + f"export const enumManifest = {body.rstrip()} as const;\n" + "export type EnumGroup = keyof typeof enumManifest.groups;\n"
    if args.check:
        return 0 if json_path.read_text(encoding="utf-8") == body and ts_path.read_text(encoding="utf-8") == ts else 1
    json_path.write_text(body, encoding="utf-8", newline="\n")
    ts_path.write_text(ts, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
