import {expect,test} from "@playwright/test";import fs from "node:fs";import {execFileSync} from "node:child_process";
const golden=JSON.parse(fs.readFileSync(new URL("../fixtures/aiPresentationFullGolden.json",import.meta.url),"utf8"));
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem("crypto-bot-language","zh"));});
const projected=(mode:string,warnings:string[]=[])=>({...golden,mode,presentation_id:`fixture-${mode}`,report:{...golden.report,mode,data_warnings:warnings},data_warnings:warnings,position_summary:mode==="POSITION_AWARE"?{source:"USER_DECLARED",sensitive_details_available:true}:{source:"NONE",sensitive_details_available:false}});
const stats=(values:number[])=>{const sorted=[...values].sort((a,b)=>a-b);return {p50_ms:sorted[Math.floor(sorted.length*.5)],p95_ms:sorted[Math.floor(sorted.length*.95)],max_ms:sorted[sorted.length-1]};};
async function authorize(page:any){await page.goto("/shadow/ai-market-analysis");await page.getByLabel("管理员令牌").fill("synthetic-admin");await page.getByRole("button",{name:"打开 Shadow 报告"}).click();await expect(page.locator(".ama-report-header")).toBeVisible();}

test("cached structured render benchmark makes zero network requests",async({page,browserName})=>{
  test.setTimeout(120_000);
  let calls=0;await page.route("**/api/ai-market-analysis/v1/presentations/latest?**",route=>{calls++;const mode=new URL(route.request().url()).searchParams.get("mode")||"FULL";return route.fulfill({contentType:"application/json",body:JSON.stringify(projected(mode))});});
  await authorize(page);await page.getByLabel("报告模式").selectOption("POSITION_AWARE");await expect(page.locator(".ama-report-header h1")).toContainText("持仓感知");await page.getByLabel("报告模式").selectOption("FULL");await expect(page.locator(".ama-report-header h1")).toContainText("完整");
  for(let i=0;i<5;i++){const mode=i%2?"FULL":"POSITION_AWARE";await page.getByLabel("报告模式").selectOption(mode);await expect(page.locator(".ama-report-header h1")).toContainText(mode==="FULL"?"完整":"持仓感知");}
  const before=calls,values:number[]=[];for(let i=0;i<30;i++){const mode=i%2?"FULL":"POSITION_AWARE";const duration=await page.evaluate(async desired=>{const start=performance.now();const select=document.querySelectorAll("select")[1] as HTMLSelectElement|null;if(!select)throw new Error("mode select absent");select.value=desired;select.dispatchEvent(new Event("change",{bubbles:true}));await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);return performance.now()-start;},mode);await expect(page.locator(".ama-report-header h1")).toContainText(mode==="FULL"?"完整":"持仓感知");values.push(duration);}
  const artifact={benchmark:"AI-6AC cached real React structured render",warmup:5,iterations:30,...stats(values),network_requests_during_measurement:calls-before,payload_bytes:Buffer.byteLength(JSON.stringify(golden)),chromium_version:await page.evaluate(()=>navigator.userAgent),browser_name:browserName,viewport:page.viewportSize(),commit:execFileSync("git",["rev-parse","HEAD"],{encoding:"utf8"}).trim(),measured_at:new Date().toISOString()};fs.mkdirSync(new URL("../../artifacts/ai6a/",import.meta.url),{recursive:true});fs.writeFileSync(new URL("../../artifacts/ai6a/cached_render_benchmark.json",import.meta.url),JSON.stringify(artifact,null,2)+"\n");expect(artifact.network_requests_during_measurement).toBe(0);expect(artifact.p95_ms).toBeLessThanOrEqual(100);
});

test("first structured desktop mobile position and warning render benchmark",async({page})=>{
  test.setTimeout(120_000);
  let active=projected("FULL");await page.route("**/api/ai-market-analysis/v1/presentations/latest?**",route=>route.fulfill({contentType:"application/json",body:JSON.stringify(active)}));const cases=[{name:"desktop_full",mode:"FULL",width:1440,warnings:[]},{name:"desktop_position",mode:"POSITION_AWARE",width:1440,warnings:[]},{name:"desktop_critical",mode:"FULL",width:1440,warnings:["CRITICAL"]},{name:"mobile_full",mode:"FULL",width:390,warnings:[]}];const results:Record<string,ReturnType<typeof stats>>={};
  for(const item of cases){const values:number[]=[];await page.setViewportSize({width:item.width,height:900});for(let i=0;i<5;i++){active=projected(item.mode,item.warnings);await page.goto("/shadow/ai-market-analysis");await page.getByLabel("报告模式").selectOption(item.mode);await page.getByLabel("管理员令牌").fill("synthetic-admin");await page.evaluate(()=>{new MutationObserver((_,observer)=>{if(document.querySelector(".ama-report-header")){const mark=performance.getEntriesByName("ama-presentation-normalized").at(-1);Reflect.set(window,"__amaFirst",mark?performance.now()-mark.startTime:NaN);observer.disconnect();}}).observe(document.body,{childList:true,subtree:true});});await page.getByRole("button",{name:"打开 Shadow 报告"}).click();await expect(page.locator(".ama-report-header")).toBeVisible();values.push(await page.evaluate(()=>Number(Reflect.get(window,"__amaFirst"))));}results[item.name]=stats(values);expect(results[item.name].max_ms).toBeLessThanOrEqual(300);}
  const artifact={benchmark:"AI-6AC first structured render after parse/normalization (network excluded)",iterations_per_case:5,payload_bytes:Buffer.byteLength(JSON.stringify(golden)),viewport_cases:cases,results,chromium_version:await page.evaluate(()=>navigator.userAgent),commit:execFileSync("git",["rev-parse","HEAD"],{encoding:"utf8"}).trim(),measured_at:new Date().toISOString()};fs.writeFileSync(new URL("../../artifacts/ai6a/first_render_benchmark.json",import.meta.url),JSON.stringify(artifact,null,2)+"\n");
});
