import { expect, test, type Page } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

test.beforeEach(async ({ page }) => { await page.addInitScript(() => localStorage.setItem("crypto-bot-language", "zh")); });

const section=(id:string,title:string)=>({section_id:id,title,body:"Synthetic audited plain text",fact_refs:["TF15_SUMMARY"],level_refs:[],scenario_refs:[],macro_refs:[],position_refs:[],uncertainties:[]});
function presentation(overrides:Record<string,unknown>={}) { const eligibility=String(overrides.eligibility||"AUDIT_PASSED_SHADOW_ONLY"); return {
  presentation_schema_version:"ai-market-presentation-v1",presentation_id:"presentation_1",instrument:String(overrides.instrument||"ETH-USDT-SWAP"),mode:String(overrides.mode||"FULL"),language:"zh-CN",report_id:"report_1234567890123456",request_id:"request_1234567890123456",context_id:"context_1234567890123456",registry_snapshot_id:"registry_1",audit_id:"audit_1234567890123456",report_schema_version:"ai-market-report-response-v2",audit_schema_version:"ai-report-audit-v2",decision_time:"2027-11-01T00:00:00Z",latest_confirmed_market_time:1825027200,generated_at:"2027-11-01T00:00:00Z",audited_at:"2027-11-01T00:01:00Z",eligibility,
  freshness:{status:String(overrides.freshness||"CURRENT"),policy_version:"ai-market-freshness-policy-v1",quality:"VALID"},latest_generated:{report_id:String(overrides.latestReport||"report_1234567890123456"),eligibility:String(overrides.latestEligibility||eligibility)},
  report:eligibility==="AUDIT_PASSED_SHADOW_ONLY"?{context_id:"context_1234567890123456",schema_version:"ai-market-report-response-v2",headline:String(overrides.headline||"Synthetic breakout retest"),market_phase:"MIXED",directional_bias:"BULLISH",confidence:"MEDIUM",language:"zh-CN",sections:[section("CONCLUSION","综合结论"),section("TF_15M","15分钟"),section("TF_1H","1小时"),section("TF_4H","4小时"),section("TF_1D","日线"),section("TF_1W","周线"),section("ORDER_FLOW","订单流"),section("KEY_LEVELS","关键位"),section("SCENARIOS","三种路径"),section("LIMITATIONS","数据限制")],key_levels:[],scenarios:[],data_warnings:overrides.warnings||[],source_versions:{facts:"v1"},model:"fake-ai4",prompt_version:"prompt-v2"}:null,
  audit_summary:eligibility==="AUDIT_NOT_FOUND"?null:{status:eligibility.includes("FAILED")?"FAILED":eligibility.includes("ERROR")?"ERROR":"PASSED",overall_score:100,promotion_eligible:eligibility==="AUDIT_PASSED_SHADOW_ONLY",ratios:{numeric_grounding:1,reference_support:1,level_field_coverage:1,scenario_field_coverage:1,invalidation_coverage:1,warning_coverage:1},hard_failures:eligibility.includes("FAILED")?["UNSUPPORTED_CLAIM"]:[],hard_failure_count:eligibility.includes("FAILED")?1:0,warnings:[],policy_version:"policy-v2"},
  referenced_facts:["15","1H","4H","1D","1W"].map(tf=>({fact_id:`TF${tf}_SUMMARY`,category:"TIMEFRAME",label:`${tf} summary`,value:{trend:tf==="1W"?"BEARISH":"BULLISH",structure:"RANGE",confirmed_close:1900,ma_ordering:"MIXED",momentum:"POSITIVE",volume_regime:"EXPANDING",support:1880,resistance:1925,invalidation:1870},quality:"VALID",source:"FROZEN_CONTEXT",context_pointer:`/timeframes/${tf}`})).concat([{fact_id:"FLOW_PHASE_01",category:"ORDER_FLOW",label:"Impulse",value:{price_change:2.1,cvd:"POSITIVE",oi:"FALLING",funding:"NORMAL",basis:"NORMAL",liquidation:"SHORT",primary_attribution:"SHORT_COVERING_DOMINANT",alternative:"ACTIVE_BUYING_CONTRIBUTED",confidence:"MEDIUM",quality:"VALID"},quality:"VALID",source:"FROZEN_CONTEXT",context_pointer:"/orderflow/0"}]),
  referenced_levels:[{level_id:"level_1",asserted_role:"SUPPORT",asserted_state:"FLIPPED",asserted_strength:"MAJOR",asserted_timeframe:"4H",asserted_dynamic:true,analysis_text:"Synthetic dynamic support"},{level_id:"level_2",asserted_role:"PIVOT",asserted_state:"ACTIVE",asserted_strength:"WEAK",asserted_timeframe:"MULTI",asserted_dynamic:false,analysis_text:"Synthetic weak pivot"}],
  referenced_scenarios:["BULLISH_CONTINUATION","NORMAL_RETEST","FAILED_BREAKOUT"].map((type,index)=>({scenario_id:`scenario_${index}`,scenario_type:type,direction:index===2?"DOWN":"UP",likelihood:index===2?"LOW":"MEDIUM",trigger_text:"Synthetic trigger",confirmation_text:"Synthetic confirmation",expected_path_text:"level_1 -> level_2",target_level_refs:["level_2"],invalidation_text:"Confirmed close invalidation",invalidation_timeframe:"15m",confirmed_close_required:true,volume_confirmation_text:"Volume confirms",cvd_confirmation_text:"CVD confirms",oi_confirmation_text:"OI confirms",funding_basis_confirmation_text:"Funding and basis not extreme",contradicting_evidence_text:"Synthetic counterevidence"})),
  referenced_macro:overrides.macro||[],position_summary:overrides.position||{source:"NONE",sensitive_details_available:false},data_warnings:overrides.warnings||[],health_summary:{reports_enabled:true,shadow_only:true,queue_depth:0,failed_count:0},source_versions:{facts:"v1"},presentation_hash:"hash_1",
}; }
async function open(page:Page,value:Record<string,unknown>=presentation(),status=200,delay=0){await page.route("**/api/ai-market-analysis/v1/presentations/latest?**",async route=>{if(delay)await new Promise(r=>setTimeout(r,delay));await route.fulfill({status,contentType:"application/json",body:JSON.stringify(status===200?value:{error:{code:`HTTP_${status}`,message:"sanitized"}})});});await page.goto("/shadow/ai-market-analysis");await page.getByLabel("管理员令牌").fill("synthetic-admin");await page.getByRole("button",{name:"打开 Shadow 报告"}).click();}

test("unauthorized starts without report request",async({page})=>{let calls=0;await page.route("**/api/ai-market-analysis/**",r=>{calls++;return r.abort();});await page.goto("/shadow/ai-market-analysis");await expect(page.getByLabel("管理员令牌")).toBeVisible();expect(calls).toBe(0);});
for(const [eligibility,text] of [["AUDIT_PENDING","正在等待审计"],["AUDIT_FAILED","审计未通过"],["AUDIT_ERROR","审计系统错误"],["AUDIT_NOT_FOUND","尚未创建审计"],["AUDIT_SCHEMA_UPGRADE_REQUIRED","旧 Schema 需要升级"]] as const)test(`${eligibility} fails closed`,async({page})=>{await open(page,presentation({eligibility}));await expect(page.getByRole("heading",{name:text})).toBeVisible();await expect(page.getByText("Synthetic breakout retest")).toHaveCount(0);});
for(const freshness of ["CURRENT","AGING","STALE","SUPERSEDED","UNKNOWN"])test(`passed ${freshness} badge`,async({page})=>{await open(page,presentation({freshness}));await expect(page.locator(`.ama-${freshness.toLowerCase()}`)).toBeVisible();});
for(const instrument of ["BTC-USDT-SWAP","ETH-USDT-SWAP","SOL-USDT-SWAP"])test(`${instrument} isolated`,async({page})=>{await open(page,presentation({instrument}));await page.getByLabel("Instrument").selectOption(instrument);await expect(page.getByRole("heading",{name:new RegExp(instrument)})).toBeVisible();});
for(const mode of ["QUICK","FULL","POSITION_AWARE"])test(`${mode} cache isolated`,async({page})=>{await open(page,presentation({mode}));await page.getByLabel("Mode").selectOption(mode);await expect(page.getByRole("heading",{name:new RegExp(mode)})).toBeVisible();});
for(const status of [401,429,500])test(`sanitized HTTP ${status}`,async({page})=>{await open(page,presentation(),status);await expect(page.getByRole("alert")).toContainText(String(status));});
test("network error explicit",async({page})=>{await page.route("**/api/ai-market-analysis/**",r=>r.abort());await page.goto("/shadow/ai-market-analysis");await page.getByLabel("管理员令牌").fill("x");await page.getByRole("button",{name:"打开 Shadow 报告"}).click();await expect(page.getByRole("alert")).toBeVisible();});
test("old passed and new pending separated",async({page})=>{await open(page,presentation({latestReport:"new_pending",latestEligibility:"AUDIT_PENDING"}));await expect(page.getByText("这是旧的已审计报告；更新报告仍在审计或未通过。")).toBeVisible();});
for(const source of ["NONE","PAPER","USER_DECLARED"])test(`${source} position privacy`,async({page})=>{await open(page,presentation({position:{source,sensitive_details_available:source!=="NONE"}}));if(source==="NONE")await expect(page.getByText("未提供持仓信息。")).toBeVisible();else await expect(page.getByRole("button",{name:"显示持仓细节"})).toBeVisible();});
test("no macro empty state",async({page})=>{await open(page);await expect(page.getByText("本次未加入已验证宏观证据。")).toBeVisible();});
test("safe macro link",async({page})=>{await open(page,presentation({macro:[{title:"Synthetic macro",factual_summary:"Fixture only",url:"https://example.com/source"}]}));await expect(page.getByRole("link",{name:/Verified source/})).toHaveAttribute("rel","noopener noreferrer");});
for(const warning of ["CRITICAL_WATERMARK_MISMATCH","CVD_GAP","OI_GAP","PARTIAL_DATA"])test(`${warning} visible warning`,async({page})=>{await open(page,presentation({warnings:[warning]}));await expect(page.locator(".ama-warnings")).toContainText(warning.split("_").join(" "));});
test("five timeframe rows",async({page})=>{await open(page);await expect(page.locator("table tbody tr")).toHaveCount(5);});
test("evidence drawer bounded",async({page})=>{await open(page);await page.getByText(/查看证据/).first().click();await expect(page.locator(".ama-evidence li").first()).toContainText("TF15_SUMMARY");});
test("audit scorecard and provenance",async({page})=>{await open(page);await expect(page.getByRole("heading",{name:"审计评分卡"})).toBeVisible();await page.getByText("来源与版本").click();await expect(page.getByText("prompt-v2")).toBeVisible();});
test("three scenarios expand without blocking",async({page})=>{await open(page);await expect(page.locator(".ama-scenario")).toHaveCount(3);const elapsed=await page.evaluate(()=>{const start=performance.now();(document.querySelector(".ama-scenario") as HTMLDetailsElement).open=true;return performance.now()-start;});console.log(`AI6A_SCENARIO_EXPAND_MS=${elapsed.toFixed(3)}`);expect(elapsed).toBeLessThan(50);});
test("first structured render and evidence interaction budget",async({page})=>{await page.route("**/api/ai-market-analysis/v1/presentations/latest?**",route=>route.fulfill({contentType:"application/json",body:JSON.stringify(presentation())}));await page.goto("/shadow/ai-market-analysis");await page.getByLabel("管理员令牌").fill("x");await page.evaluate(()=>{Reflect.set(window,"__amaStart",performance.now());new MutationObserver((_,observer)=>{if(document.querySelector(".ama-report-header")){Reflect.set(window,"__amaRender",performance.now()-Number(Reflect.get(window,"__amaStart")));observer.disconnect();}}).observe(document.body,{childList:true,subtree:true});});await page.getByRole("button",{name:"打开 Shadow 报告"}).click();await expect(page.locator(".ama-report-header")).toBeVisible();const render=await page.evaluate(()=>Number(Reflect.get(window,"__amaRender")));expect(render).toBeLessThan(300);const drawer=await page.evaluate(()=>{const start=performance.now();(document.querySelector(".ama-evidence") as HTMLDetailsElement).open=true;return performance.now()-start;});console.log(`AI6A_FIRST_RENDER_MS=${render.toFixed(3)} AI6A_EVIDENCE_DRAWER_MS=${drawer.toFixed(3)}`);expect(drawer).toBeLessThan(50);});
test("provider HTML inert",async({page})=>{await open(page,presentation({headline:"<script>window.pwned=1</script>"}));expect(await page.evaluate(()=>Reflect.get(window,"pwned"))).toBeUndefined();await expect(page.getByText("<script>window.pwned=1</script>")).toBeVisible();});
test("English UI does not translate audited Chinese body",async({page})=>{await page.addInitScript(()=>localStorage.setItem("crypto-bot-language","en"));await page.route("**/api/ai-market-analysis/v1/presentations/latest?**",route=>route.fulfill({contentType:"application/json",body:JSON.stringify(presentation())}));await page.goto("/shadow/ai-market-analysis");await page.getByLabel("Admin token").fill("x");await page.getByRole("button",{name:"Open shadow report"}).click();await expect(page.getByRole("heading",{name:"AI Market Analysis"})).toBeVisible();await expect(page.getByRole("heading",{name:"综合结论"})).toBeVisible();});
test("late ETH cannot replace BTC",async({page})=>{let count=0;await page.route("**/api/ai-market-analysis/v1/presentations/latest?**",async route=>{count++;const inst=new URL(route.request().url()).searchParams.get("instrument")||"ETH-USDT-SWAP";if(count===1)await new Promise(r=>setTimeout(r,250));await route.fulfill({contentType:"application/json",body:JSON.stringify(presentation({instrument:inst}))});});await page.goto("/shadow/ai-market-analysis");await page.getByLabel("管理员令牌").fill("x");await page.getByRole("button",{name:"打开 Shadow 报告"}).click();await page.getByLabel("Instrument").selectOption("BTC-USDT-SWAP");await expect(page.getByRole("heading",{name:/BTC-USDT-SWAP/})).toBeVisible();await page.waitForTimeout(300);await expect(page.getByRole("heading",{name:/BTC-USDT-SWAP/})).toBeVisible();});
test("keyboard and accessible labels",async({page})=>{await open(page);await page.keyboard.press("Tab");expect(await page.locator(":focus").count()).toBe(1);await expect(page.locator("table caption")).toHaveText("周期矩阵");});
test("automated accessibility audit",async({page})=>{await open(page);const results=await new AxeBuilder({page}).analyze();expect(results.violations.filter(item=>item.impact==="critical"||item.impact==="serious")).toEqual([]);});
for(const width of [1440,1024,768,390])test(`responsive ${width}px`,async({page})=>{await page.setViewportSize({width,height:900});await open(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);});
test("legacy route default",async({page})=>{await page.route("**/*",route=>{const url=new URL(route.request().url());return url.origin!=="http://127.0.0.1:4173"||url.pathname.startsWith("/api/")?route.abort():route.continue();});await page.goto("/");await expect(page.locator('[data-route="market"]')).toBeAttached();});
