import { useState } from "react";
import { phase4Api, post, pct } from "./api";

export default function RobustnessPanel() {
  const [inputRun, setInputRun] = useState(""); const [simulations, setSimulations] = useState(1000); const [seed, setSeed] = useState(42);
  const [runId, setRunId] = useState<number | null>(null); const [data, setData] = useState<any>(null); const [message, setMessage] = useState("");
  async function run() { try { const x = await post<{ id: number }>("/api/robustness/run", { input_run_id: +inputRun, simulation_count: simulations, random_seed: seed, fee_multipliers: [.5, 1, 1.5, 2], slippage_multipliers: [.5, 1, 1.5, 2], missed_trade_rates: [0, .05, .1, .2], execution_delay_bars: [0, 1, 2] }); setRunId(x.id); setMessage(`Robustness run #${x.id} queued.`); } catch (e) { setMessage(e instanceof Error ? e.message : "Run failed"); } }
  async function load() { if (runId) try { setData(await phase4Api(`/api/robustness/${runId}`)); } catch (e) { setMessage(e instanceof Error ? e.message : "Not ready"); } }
  const r = data?.result || data;
  return <section className="phase4-card"><div className="phase4-head"><div><span className="eyebrow">Reproducible sample perturbation · maximum 5,000 simulations</span><h2>Monte Carlo & Bootstrap Robustness</h2></div></div><div className="phase4-controls"><label>Input Run<input value={inputRun} onChange={e => setInputRun(e.target.value)} placeholder="Backtest ID" /></label><label>Simulations<input type="number" min="1" max="5000" value={simulations} onChange={e => setSimulations(+e.target.value)} /></label><label>Random Seed<input type="number" value={seed} onChange={e => setSeed(+e.target.value)} /></label><button onClick={run}>Run Robustness</button>{runId && <button onClick={load}>Refresh Result</button>}</div>{message && <div className="research-alert warning">{message}</div>}{r?.status === "COMPLETED" ? <><div className="research-metrics"><article><span>Median Return</span><strong>{pct(r.median_return)}</strong></article><article><span>5th / 95th Return</span><strong>{pct(r.return_percentiles?.p5)} / {pct(r.return_percentiles?.p95)}</strong></article><article><span>Median Drawdown</span><strong>{pct(r.median_drawdown)}</strong></article><article><span>95th Drawdown</span><strong>{pct(r.p95_drawdown)}</strong></article><article><span>Positive Probability</span><strong>{pct(r.probability_positive_return * 100)}</strong></article><article><span>Risk of Ruin</span><strong>{pct(r.risk_of_ruin * 100)}</strong></article></div><div className="distribution-strip">{(r.returns || []).slice(0, 300).map((x: number, i: number) => <i key={i} className={x >= 0 ? "positive-bar" : "negative-bar"} style={{ height: `${Math.min(100, Math.abs(x) * 3 + 3)}%` }} />)}</div><p className="method-note">{r.disclaimer}</p></> : <div className="research-empty compact">Select a completed backtest with actual trades. Empty samples are reported as Insufficient Data.</div>}</section>;
}
